name: tenant

hosts:
  - "*.uds.dev"

# Development certificate and key *.admin.uds.dev (127.0.0.1)
# Publicly available, not for use in production environments
tls:
  cert: |
    -----BEGIN CERTIFICATE-----
    MIIGJTCCBQ2gAwIBAgIRAOdpAaehw6DVJ36q7EuGM6owDQYJKoZIhvcNAQELBQAw
    gY8xCzAJBgNVBAYTAkdCMRswGQYDVQQIExJHcmVhdGVyIE1hbmNoZXN0ZXIxEDAO
    BgNVBAcTB1NhbGZvcmQxGDAWBgNVBAoTD1NlY3RpZ28gTGltaXRlZDE3MDUGA1UE
    AxMuU2VjdGlnbyBSU0EgRG9tYWluIFZhbGlkYXRpb24gU2VjdXJlIFNlcnZlciBD
    QTAeFw0yMzEwMTcwMDAwMDBaFw0yNDExMTYyMzU5NTlaMBQxEjAQBgNVBAMMCSou
    dWRzLmRldjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAJghSe/r1qIG
    7ReGnwIwZVc2jBRxxpCdvMYORz66plKm/9+9f0Ud0xcymfUaLGWe9k2veeRBPbY6
    GJHyjdxup/sMpaCWBLY7vnmopodKmnzsGY9fj48zxBCvEChmylI35Hb8vyoYlhL+
    k7klZEOJHbXoDW2pQnBugthvVuZmmckkGhWHjyv2l5gf5SDJRQrsPY7KAv+Exr7Z
    u9+Dsm4YACSjF7XZwv3FVl0MbQhtbFTkQN0RSG8yTZ8LTFCyvC3Hbh291u/cyo+v
    qUwWfbCGYk3GJko4xj8bdl6qih5hw0Gt4o9TjS+nZpAL01XbCfKO0/HCOr+cM6Au
    dnVm5zUz8k0CAwEAAaOCAvQwggLwMB8GA1UdIwQYMBaAFI2MXsRUrYrhd+mb+ZsF
    4bgBjWHhMB0GA1UdDgQWBBQYS8SI7Hqw/LUjkp+I36ChMkJjbzAOBgNVHQ8BAf8E
    BAMCBaAwDAYDVR0TAQH/BAIwADAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUH
    AwIwSQYDVR0gBEIwQDA0BgsrBgEEAbIxAQICBzAlMCMGCCsGAQUFBwIBFhdodHRw
    czovL3NlY3RpZ28uY29tL0NQUzAIBgZngQwBAgEwgYQGCCsGAQUFBwEBBHgwdjBP
    BggrBgEFBQcwAoZDaHR0cDovL2NydC5zZWN0aWdvLmNvbS9TZWN0aWdvUlNBRG9t
    YWluVmFsaWRhdGlvblNlY3VyZVNlcnZlckNBLmNydDAjBggrBgEFBQcwAYYXaHR0
    cDovL29jc3Auc2VjdGlnby5jb20wHQYDVR0RBBYwFIIJKi51ZHMuZGV2ggd1ZHMu
    ZGV2MIIBfgYKKwYBBAHWeQIEAgSCAW4EggFqAWgAdgB2/4g/Crb7lVHCYcz1h7o0
    tKTNuyncaEIKn+ZnTFo6dAAAAYs8UaCDAAAEAwBHMEUCIG9mn+DGpZufRylyaJRN
    2UaPnNah7cm0MiYVnnWas6e6AiEA8r2LdHNRXGZf/CM8imbSzSvylQl4uaCCSGPg
    erG1WrkAdgDatr9rP7W2Ip+bwrtca+hwkXFsu1GEhTS9pD0wSNf7qwAAAYs8UaDc
    AAAEAwBHMEUCIQCHLoL2/tehz3XTvopX5emHiCyqbA2u+A1AqMeedU660gIgKKg0
    RmCzdqkNdzoMpgDoEgEJao2U8Yu8JXakDhoUAlwAdgDuzdBk1dsazsVct520zROi
    ModGfLzs3sNRSFlGcR+1mwAAAYs8UaEBAAAEAwBHMEUCIHdsOtLkRKq6APeyGuil
    RxL/o3zCKqSOU8joJTlOPy22AiEAoFytoFqYeNMPJ+8dGQynl4GfmdAq2+fPoxeQ
    zhrTKj8wDQYJKoZIhvcNAQELBQADggEBAJ8rXPgjtsCTFCksdJrtbvJ+cUBObUPG
    gOBNQJ6tsdkGCu6LDI6e++Tot7CBB2MR48Pi3CI6n/KjMIM4bx8GvUnKUo9sKtbB
    ZUBPI7/uZyrE+lnFqOSgz4pAVsWKbQcuGJpBzpTIZGSPORf8dzWmBt+ptmiv1o2h
    5l3xX+P3L9cRbIjNUwuuLwHcyVRxfuwCOPHa/qYNMW+f1nEoiYdm/knOtYrVy/F3
    7tf+Oys2F2fyix5JumbCp+SO5yj/WvV282sCKVZKzdg8FJWupubd+frO6dejPlTG
    koPDwo8RzJ4jTp1cWt5l4R1k1qluie+wh9sNOKlBVXFHSVS7H1Cnf90=
    -----END CERTIFICATE-----


  key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCYIUnv69aiBu0X
    hp8CMGVXNowUccaQnbzGDkc+uqZSpv/fvX9FHdMXMpn1GixlnvZNr3nkQT22OhiR
    8o3cbqf7DKWglgS2O755qKaHSpp87BmPX4+PM8QQrxAoZspSN+R2/L8qGJYS/pO5
    JWRDiR216A1tqUJwboLYb1bmZpnJJBoVh48r9peYH+UgyUUK7D2OygL/hMa+2bvf
    g7JuGAAkoxe12cL9xVZdDG0IbWxU5EDdEUhvMk2fC0xQsrwtx24dvdbv3MqPr6lM
    Fn2whmJNxiZKOMY/G3ZeqooeYcNBreKPU40vp2aQC9NV2wnyjtPxwjq/nDOgLnZ1
    Zuc1M/JNAgMBAAECggEARDitbQOwYUHE4gdzWCp2z7j88ZAiMSkjhhfSGE3gl3Ef
    jujuYYLh7mW5SAKgRUQXhTf7bAJb19POv+hreJ5BA2KlBdIws74wCWO5pjMs+3dv
    cO20Nc5LjwXKs6uA8ITzFe77FTgoWMVEXsNnZqffJHu3ReWhD0VntQKdED6TmXC/
    nvBA4pvGDeA/Gd5e0kec77SNxAcJIs0ltnZ/Dcm18Y6d1WY7ljL5k4z2JTpXZcBo
    bm/BTcA9wXAhQUAC5YJix7E9Js2FvAHdxU5jAXQk0o3vI4WgByBMc9neGg/R9Hve
    25J/dPJpIYGxq2ywyKDZxhxmQc+uvl53rmXsbHd+6wKBgQDJXU4l/fJoci5PLqAJ
    hL6jNugvNRKZXwFCc/4X0R/xdWkD3OX5IukPc7+bCcpoBgzuAqDqcxNek+03m5P6
    THj6fthzYHrDZy5AhzmH9l5NjipJwltqBIDEOH0Dlv1/qF+zfIgbA8VJ0MZRKcSk
    JbfeKg1Ujl7ACUUJYIwR7zdGqwKBgQDBaC3qFsribIt3n5SddL6UhHniUKSlHs9R
    wEG43wyx8d8AIYLOz9USKOVS24iALRkUDR6xyzTDMDnC8BarFHc12UzoLtDVyUw+
    /u9urNdTu6kjmdCe3xnbWDaKl82XqGTH0Yt/NRHZm0s/So7xFqbvYM6PzruCwRLY
    M39uFrGK5wKBgEhTz2IuGQgTGzct1CYXHDKb4kIymf+k9FreNwJvBz4/ofzVN3WJ
    aJU4SjZyCdXbdoF3SD1uICL0l1xF8Z0SItI3BaBLo0zUnvRmne+MOss4qU/dE+C8
    xVO1xpGnhl54KAfcTzcE37Rn3RQCILOlKKoQCMG6caYgrj90AlvexMgJAoGBAIJA
    DuvffbMPNr3REt0XimGq9gqcFMW/AhAkUh6W2I3ePjhwWQ++l9grAoXSoxLvTDxc
    uZczKs1o5P2LgzikB8SUG18iaDIR5u9l8QmwDTOu5jG7nOvhhCBcQB8GLMc9+OE5
    FaENtH/APeTZ6Xojrzj3ESV4LH/aVz6TL/aMAfVxAoGBAKSiEif4b+M7pSo95fzJ
    xjzp03hkcZ0JreU1DOyIZi9hfttgzvkLnI+KN82500fFhNGndXsWFDC5tYHQmFCh
    UEX4Co+Z1iGEfi3KRMarb90LhMJziaUmT9Ufa/DiuoklwgP+v6DqdBB0zhMzDZBz
    YyfzHvCdJsBCP0WYvMqaejeO
    -----END PRIVATE KEY-----
