name: admin

hosts:
  - "*.admin.uds.dev"

# Development certificate and key *.admin.uds.dev (127.0.0.1)
# Publicly available, not for use in production environments
tls:
  cert: |
    -----BEGIN CERTIFICATE-----
    MIIGNjCCBR6gAwIBAgIQAiYjJlL0FbVZMjdXvgxaqzANBgkqhkiG9w0BAQsFADCB
    jzELMAkGA1UEBhMCR0IxGzAZBgNVBAgTEkdyZWF0ZXIgTWFuY2hlc3RlcjEQMA4G
    A1UEBxMHU2FsZm9yZDEYMBYGA1UEChMPU2VjdGlnbyBMaW1pdGVkMTcwNQYDVQQD
    Ey5TZWN0aWdvIFJTQSBEb21haW4gVmFsaWRhdGlvbiBTZWN1cmUgU2VydmVyIENB
    MB4XDTIzMTAxNzAwMDAwMFoXDTI0MTExNjIzNTk1OVowGjEYMBYGA1UEAwwPKi5h
    ZG1pbi51ZHMuZGV2MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlmg0
    UuR6/ZA/wDStZ9KFYtVpJDrtC3vOcAujqwqVX3nIEbyDYMYmnqL/FVzCXOemtd6M
    H1YzsiXPMJy4UXe3/QXxtaSx8gf3TBJQVclzp4zV4A91N6PLSEJZ0AOh5omOTrYz
    48TdEVksasltowythWZhavfE8mmDpZr+iZbbES4m9rS1zQayCccabwf3MMpjIpZW
    hiJCiudTKUHkmRNhCGc3cqyyM7e4LH8QRTDj7/54WfVUUVWKMT7FjkMcbtLsgN7X
    Iax0MUL3HCZAJpe9XSkEYhAKPFf546CvivyJsY7OUKq7cWtrihgA75QiW+uzSXL5
    WiAHpGh7dTbZ532cRwIDAQABo4IDADCCAvwwHwYDVR0jBBgwFoAUjYxexFStiuF3
    6Zv5mwXhuAGNYeEwHQYDVR0OBBYEFJ8CGjiSdRrcoeIYDDmnM88gonXfMA4GA1Ud
    DwEB/wQEAwIFoDAMBgNVHRMBAf8EAjAAMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggr
    BgEFBQcDAjBJBgNVHSAEQjBAMDQGCysGAQQBsjEBAgIHMCUwIwYIKwYBBQUHAgEW
    F2h0dHBzOi8vc2VjdGlnby5jb20vQ1BTMAgGBmeBDAECATCBhAYIKwYBBQUHAQEE
    eDB2ME8GCCsGAQUFBzAChkNodHRwOi8vY3J0LnNlY3RpZ28uY29tL1NlY3RpZ29S
    U0FEb21haW5WYWxpZGF0aW9uU2VjdXJlU2VydmVyQ0EuY3J0MCMGCCsGAQUFBzAB
    hhdodHRwOi8vb2NzcC5zZWN0aWdvLmNvbTApBgNVHREEIjAggg8qLmFkbWluLnVk
    cy5kZXaCDWFkbWluLnVkcy5kZXYwggF+BgorBgEEAdZ5AgQCBIIBbgSCAWoBaAB3
    AHb/iD8KtvuVUcJhzPWHujS0pM27KdxoQgqf5mdMWjp0AAABizxPrNQAAAQDAEgw
    RgIhAKpiYqs45vUe7SgVrWtDMdGe1gF7q1ZDCOvQrLAZyYj5AiEAxpWNxc4mWccW
    J13+ECh24sfCirQRsVko9aMzGo+8RNQAdQDatr9rP7W2Ip+bwrtca+hwkXFsu1GE
    hTS9pD0wSNf7qwAAAYs8T60mAAAEAwBGMEQCIEJ2sCw/Mk1bTVZIky0JZdAcrSmo
    sN0L/336YPd7Usp0AiBwgATvhROYm9SDHNEKOKJ39F/cuVZxj3dpTILN4epk4QB2
    AO7N0GTV2xrOxVy3nbTNE6Iyh0Z8vOzew1FIWUZxH7WbAAABizxPrPsAAAQDAEcw
    RQIhAK0S6itxp+EasbG9+eCEad1m7X2WwZ45Gkyd9cwqFIo1AiBBz9Ny9m3XB+YV
    ndXZS2VkONEtgLFF3H/0r0IB56s9ITANBgkqhkiG9w0BAQsFAAOCAQEAYoduuqNR
    FlAiO3D3DnMAIa7qU2R/ExBDdcu/iC+nGLBLdLro2SwWdw4ViN17xvUIW/PfEQXp
    Qw5rFnjzp9qmdqM5derZvGJEVkq1knmb5Ah395QXkrnDB6UGVB15KP8jJb3EgSIF
    AqzoaWQPXeH66GNZA70nNWtHMrRhivvV4q4SlK6FBp4uq8KSfThvb82fULTaKPxd
    soQ/0NebOvAhRfYoXlbbu3Wp6rqIe2wgkF69U5/MmC3cKHDBxQ75LQ8ckeqXVHJx
    gHvgSQMkl+O42yvEUzYJ6cBz2d8llVxHdeucjT++v7dgkU5k6T+VF1sTgoh+y+s3
    ONNt9auWOcCpyw==
    -----END CERTIFICATE-----

  key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCWaDRS5Hr9kD/A
    NK1n0oVi1WkkOu0Le85wC6OrCpVfecgRvINgxiaeov8VXMJc56a13owfVjOyJc8w
    nLhRd7f9BfG1pLHyB/dMElBVyXOnjNXgD3U3o8tIQlnQA6HmiY5OtjPjxN0RWSxq
    yW2jDK2FZmFq98TyaYOlmv6JltsRLib2tLXNBrIJxxpvB/cwymMillaGIkKK51Mp
    QeSZE2EIZzdyrLIzt7gsfxBFMOPv/nhZ9VRRVYoxPsWOQxxu0uyA3tchrHQxQvcc
    JkAml71dKQRiEAo8V/njoK+K/Imxjs5Qqrtxa2uKGADvlCJb67NJcvlaIAekaHt1
    NtnnfZxHAgMBAAECggEAEJ1XNlbt7SermyhWhXMAcBACCtIFkHCvN7pZbJIBOShD
    PQ5VdvG8n2aDBhGWmNuwE0QPt4B2unWpwwV06O7wIJ+w+S9FxuYxX7JgNHHJ+Fa6
    44LhoHFUCdnmgO99yXElirVe2wjKoNl4ah1xIoNKgcNy/HV9SIf2VmteNcW30lha
    5sJB4kdHzxqiKeOELxmWw16crSu2XWKnT59+FjTzq7mY2bz86gGTuDVT6CXgbo97
    IDhP56xizJae3pKm5E7+MGgmnx2+9a5yiezTMUG6AlQywTq8lVxOeMgUfCOUKQxg
    /lLwxCKUiRlNbUC1m0ozh1kMY5WYR0Ui7Sbu499bxQKBgQDOKdAPieqrKVrXWha7
    tdezx1WE4pBOB9GwmXE2MOJp75LNGAHqxq/dV8VlnvM8vsKie0YzBUQoYsXqqpOk
    h8Y+siBO6h61i7inKbNPTOhcSDMf4oTVlY/DYIOyWGiteHFMfU0HbnBnLsj+Qzt5
    3S9yLxqRuYz3j6zcjp9aIWMN3QKBgQC6w/n3qcakroMYnJ5FhNJnm/yoakDDg+Em
    yVr5EN1SYGjlXXvraBAM+zJsGHvnf+GD8pzO8MoYGKVS3UQ8Vl8tctzoG60Aa/UP
    oP+a3aX/v0oxCnZCtEtJVs2p5UrqnFsolWWxEu8coET3g8OdO4CNf/Q8HDL0d+hL
    B9YtDWbKcwKBgCG8+/yfAFVUZjZZ2uCLKKqWE2u0vBLY+rrg0YMhytu1RhvkMuQd
    8cfSRk6UDZBCU43NiLZuxTGqwGLf2VuSkKHP+rOPYsko/WX10A9JMblwY1Vzd3OQ
    jz9U+xhjmXXSARCYbNOrgh+Qq3nYvNH7nXkdNkbky6nzzEEn4fIZBqHNAoGAQCSG
    eRSJ8I0u4QkJIn8XdBYSlBTJ4Vwtu5Bz+g5ctKn/3KZapOK8gHjVPGK8SymUXii4
    yinQfq4YOXlcsgxH6+gDDoRSyk5Jf/CfWKS/GjKsXGNncklRggKZ57ukGydP94Q3
    xLToAkDY7tkGGb4RzIchbnOQ3H1B/mLWn+p2XxkCgYEAvheedlK2QewOzrYdPLJ8
    olh9orNQEDnk2MLAKORHnNz7EoMItEYGOF/y/LT93VY4rwQyAflm+McmoVgeAl6q
    OWyc4VYaQDMvebCVE7ipuf0vca6u7NgZoqA95BNP4HNBCdGe6uFlY1ojdRN9MvMY
    hZaXdCwIL5o0BZPSnljgEIs=
    -----END PRIVATE KEY-----
