# The gateway name prefix
name: change-me

domain: "uds.dev"

# Hosts to add to this gateway, these will be in the format <host>.<domain>, e.g. *.uds.dev
hosts:
  - "*"

tls:
  # Enable TLS passthrough mode for this gateway if true
  enablePassthrough: false

  # The secret name for the TLS certificate when not using passthrough mode
  secretName: gw-cert
